version: '3'
services:
  dadbot:
    image: dad_bot:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        RUST_BUILDER: rust:1.59.0-bullseye
        PROD_IMAGE_TAG: focal
        S6_OVERLAY_VERSION: v2.2.0.3
